name: Code_I2
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=24.0
  - python=3.10.14
  - pip:
      - corrfitter==8.2
      - gvar==11.11.17
      - h5py==3.10.0
      - lsqfit==13.0.3
      - numpy==1.26.1
      - scipy==1.13.1
      - matplotlib==3.5.2
